export const GET_ALL_CARS = 'GET_ALL_CARS';
export const GET_ONE_CAR = 'GET_ONE_CAR';
export const ADD_CAR_TO_COMPARE = 'ADD_CAR_TO_COMPARE';
export const REMOVE_CAR_FROM_COMPARE = 'REMOVE_CAR_FROM_COMPARE';
